apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: releaseflow-ingress
  namespace: releaseflow
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: releaseflow.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: releaseflow-service
                port:
                  number: 5000
